#!/usr/bin/env python3
"""
Apply patch version upgrades from a generated report.
This script reads the JSON report and updates package.json files accordingly.
"""

import argparse
import json
import os
import shutil
import sys
import time
from pathlib import Path
from typing import Dict, List


def create_backup(package_json: Path) -> Path:
    """Create a backup of package.json and return backup path."""
    backup_dir = package_json.parent / f".package-json-backups-{int(time.time())}"
    backup_dir.mkdir(parents=True, exist_ok=True)
    
    backup_file = backup_dir / package_json.name
    shutil.copy2(package_json, backup_file)
    return backup_file


def apply_upgrades(repo_root: Path, upgrades: List[Dict], create_backups: bool = False):
    """Apply upgrades to package.json files."""
    # Group upgrades by file location
    by_location: Dict[str, List[Dict]] = {}
    for upgrade in upgrades:
        location = upgrade['location']
        if location not in by_location:
            by_location[location] = []
        by_location[location].append(upgrade)
    
    applied_count = 0
    backup_dirs = set()
    
    for location, location_upgrades in by_location.items():
        package_json = repo_root / location
        
        if not package_json.exists():
            print(f"Warning: {location} not found, skipping", file=sys.stderr)
            continue
        
        # Create backup
        if create_backups:
            backup_file = create_backup(package_json)
            backup_dirs.add(backup_file.parent)
            print(f"Backed up {location} to {backup_file}")
        
        # Load package.json
        try:
            with open(package_json, 'r') as f:
                data = json.load(f)
        except (json.JSONDecodeError, IOError) as e:
            print(f"Error reading {location}: {e}", file=sys.stderr)
            continue
        
        # Apply upgrades
        modified = False
        for upgrade in location_upgrades:
            package = upgrade['package']
            dep_type = upgrade['type']
            proposed = upgrade['proposed']
            
            # Update the appropriate dependency section
            if dep_type in data:
                if package in data[dep_type]:
                    old_version = data[dep_type][package]
                    data[dep_type][package] = proposed
                    print(f"  {package}: {old_version} → {proposed}")
                    modified = True
                    applied_count += 1
        
        # Write updated package.json
        if modified:
            try:
                with open(package_json, 'w') as f:
                    json.dump(data, f, indent=2)
                    f.write('\n')  # Add trailing newline
                print(f"Updated {location}")
            except IOError as e:
                print(f"Error writing {location}: {e}", file=sys.stderr)
        else:
            print(f"No changes needed for {location}")
        
        print()
    
    if backup_dirs:
        print(f"Backups created in {len(backup_dirs)} directory/ies:")
        for backup_dir in sorted(backup_dirs):
            print(f"  {backup_dir}")
        print()
    
    print(f"Applied {applied_count} upgrades across {len(by_location)} package.json file(s)")


def main():
    parser = argparse.ArgumentParser(
        description="Apply patch version upgrades from a generated report.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
EXAMPLES:
    %(prog)s patch-upgrades.json
    %(prog)s --root /path/to/repo patch-upgrades.json
    %(prog)s --backup patch-upgrades.json
        """
    )
    
    parser.add_argument(
        'upgrades_file',
        help='Path to the patch-upgrades.json file generated by bugfix-bumper-generate.py'
    )
    parser.add_argument(
        '-r', '--root',
        default=os.getcwd(),
        help='Repository root directory (default: current directory)'
    )
    parser.add_argument(
        '--backup',
        action='store_true',
        help='Create backups of package.json files before applying changes (default: False)'
    )
    
    args = parser.parse_args()
    
    # Resolve paths
    repo_root = Path(args.root).resolve()
    upgrades_file = Path(args.upgrades_file)
    
    if not upgrades_file.is_absolute():
        # Try relative to current directory first, then relative to repo root
        if (Path.cwd() / upgrades_file).exists():
            upgrades_file = (Path.cwd() / upgrades_file).resolve()
        elif (repo_root / upgrades_file).exists():
            upgrades_file = (repo_root / upgrades_file).resolve()
        else:
            print(f"Error: Upgrades file not found: {args.upgrades_file}", file=sys.stderr)
            sys.exit(1)
    
    # Validate repository root exists (package.json files are validated when applying upgrades)
    if not repo_root.exists():
        print(f"Error: Repository root does not exist: {repo_root}", file=sys.stderr)
        print("Please specify the correct repository root with --root", file=sys.stderr)
        sys.exit(1)
    
    # Load upgrades
    try:
        with open(upgrades_file, 'r') as f:
            upgrades = json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error reading upgrades file: {e}", file=sys.stderr)
        sys.exit(1)
    
    if not isinstance(upgrades, list):
        print("Error: Invalid upgrades file format (expected JSON array)", file=sys.stderr)
        sys.exit(1)
    
    if not upgrades:
        print("No upgrades to apply.")
        sys.exit(0)
    
    print(f"Applying {len(upgrades)} upgrades from {upgrades_file}")
    print(f"Repository root: {repo_root}")
    print()
    
    # Confirm before applying
    print("This will modify the following package.json files:")
    locations = sorted(set(u['location'] for u in upgrades))
    for location in locations:
        print(f"  - {location}")
    print()
    
    response = input("Continue? [y/N]: ").strip().lower()
    if response != 'y':
        print("Cancelled.")
        sys.exit(0)
    
    print()
    
    # Apply upgrades
    apply_upgrades(repo_root, upgrades, create_backups=args.backup)


if __name__ == "__main__":
    main()
