#!/usr/bin/env python3
"""
Apply patch version upgrades from a generated report.
This script reads the JSON report and updates package.json files accordingly.
"""

import argparse
import json
import os
import sys
from pathlib import Path

from bugfix_bumper.files import restore_all_backups
from bugfix_bumper.git import gitignore_patterns
from bugfix_bumper.processing import apply_upgrades


def main():
    parser = argparse.ArgumentParser(
        description="Apply patch version upgrades from a generated report.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
EXAMPLES:
    %(prog)s patch-upgrades.json
    %(prog)s --root /path/to/repo patch-upgrades.json
    %(prog)s --backup patch-upgrades.json
    %(prog)s --restore --root /path/to/repo

NOTES:
    - Automatically regenerates package-lock.json or yarn.lock files
    - Verifies builds with npm ci or yarn install --frozen-lockfile
    - Use --restore to revert changes from .old backup files
        """,
    )

    parser.add_argument(
        "upgrades_file",
        nargs="?",
        help="Path to the patch-upgrades.json file generated by bugfix-bumper-generate.py (not required with --restore)",
    )
    parser.add_argument(
        "-r",
        "--root",
        default=os.getcwd(),
        help="Repository root directory (default: current directory)",
    )
    parser.add_argument(
        "--backup",
        action="store_true",
        help="Create backups of package.json files before applying changes (default: False)",
    )
    parser.add_argument(
        "--restore",
        action="store_true",
        help="Restore files from .old backups instead of applying upgrades",
    )

    args = parser.parse_args()

    # Handle --restore flag
    if args.restore:
        repo_root = Path(args.root).resolve()
        if not repo_root.exists():
            print(f"Error: Repository root does not exist: {repo_root}", file=sys.stderr)
            sys.exit(1)

        # Add gitignore patterns before restore, automatically removed on exit
        with gitignore_patterns(repo_root):
            restored = restore_all_backups(repo_root)
            sys.exit(0 if restored > 0 else 1)

    # Validate upgrades_file is provided when not using --restore
    if not args.upgrades_file:
        parser.error("upgrades_file is required when not using --restore")

    # Resolve paths
    repo_root = Path(args.root).resolve()
    upgrades_file = Path(args.upgrades_file)

    if not upgrades_file.is_absolute():
        # Try relative to current directory first, then relative to repo root
        if (Path.cwd() / upgrades_file).exists():
            upgrades_file = (Path.cwd() / upgrades_file).resolve()
        elif (repo_root / upgrades_file).exists():
            upgrades_file = (repo_root / upgrades_file).resolve()
        else:
            print(f"Error: Upgrades file not found: {args.upgrades_file}", file=sys.stderr)
            sys.exit(1)

    # Validate repository root exists (package.json files are validated when applying upgrades)
    if not repo_root.exists():
        print(f"Error: Repository root does not exist: {repo_root}", file=sys.stderr)
        print("Please specify the correct repository root with --root", file=sys.stderr)
        sys.exit(1)

    # Load upgrades
    try:
        with open(upgrades_file) as f:
            upgrades = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"Error reading upgrades file: {e}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(upgrades, list):
        print("Error: Invalid upgrades file format (expected JSON array)", file=sys.stderr)
        sys.exit(1)

    if not upgrades:
        print("No upgrades to apply.")
        sys.exit(0)

    print(f"Applying {len(upgrades)} upgrades from {upgrades_file}")
    print(f"Repository root: {repo_root}")
    print()

    # Confirm before applying
    print("This will modify the following package.json files:")
    locations = sorted({u["location"] for u in upgrades})
    for location in locations:
        print(f"  - {location}")
    print()

    response = input("Continue? [y/N]: ").strip().lower()
    if response != "y":
        print("Cancelled.")
        sys.exit(0)

    print()

    # Add gitignore patterns before applying upgrades, automatically removed on exit
    with gitignore_patterns(repo_root):
        # Apply upgrades
        apply_upgrades(repo_root, upgrades, create_backups=args.backup)


if __name__ == "__main__":
    main()
